LogIn_button = "//*[@class='c-user__text m-login']"
Register_button = "//*[@class='c-button']"
lastname_locator = "//*[starts-with(@id,'lastname-')]"
firstname_locator = "//*[starts-with(@id,'firstname-')]"
lastnamekana_locator = "//*[starts-with(@id,'lastnamekana-')]"
firstnamekana_locator = "//*[starts-with(@id,'firstnamekana-')]"
phonenumber_locator = "//*[starts-with(@id,'phonemobile-')]"
year_locator = "//*[@name='year']"
month_locator = "//*[@name='month']"
day_locator = "//*[@name='day']"
male_locator = "//*[contains(text(),'男性')]"
email_locator = "//body[1]/div[9]/div[2]/main[1]/div[1]/div[1]/div[1]/form[1]/div[17]/div[1]/input[1]"
comfirmationemail_locator = "//*[starts-with(@id,'confirmemail-')]"
password_locator = "//*[starts-with(@id,'password-')]"
comfirmationpassword_locator = "//*[starts-with(@id,'confirmpassword-')]"
privacy_locator = "//body[1]/div[9]/div[2]/main[1]/div[1]/div[1]/div[1]/form[1]/div[23]/label[1]"
submitregister_locator = "//*[@class='m-expand m-submit c-field']/button[@name='submit']"
membership_locator = "//body[1]/div[9]/div[2]/main[1]/div[1]/aside[1]/div[1]/nav[1]/ul[2]/li[8]/a[1]"
membershipvalidation_locator = "//h2[contains(text(),'メンバーズカード')]"
lucid_locator = "//*[starts-with(@class,'c-account-qr')][2]"
qrcode_locator = "//div[@id='qrcode']"
usernameheader_locator = "//*[@class='c-user__authenticated-welcome']"
usernameheaderlist_locator = "//*[@class='c-tooltip__body']"
logoutbutton_locator = "//*[@class='c-tooltip__body']//a[contains(@href,'Logout')]"
emaillogin_locator = "//*[starts-with(@data-component-id,'i_')]/input"
passwordlogin_locator = "//*[starts-with(@id,'password-')]"
submitlogin_locator = "//form[@name='login']/div/button"
addproduct_locator = "//*[@class='c-product-add-bag']"
gotocartbutton_locator = "//*[@class='c-button  c-add-cart__goto-button']"
productname_locator = "//*[@class='c-product-main__name']"
search_locator = "//*[@class='l-header__search-cta']/button"
searchtext_locator = "//*[@class='c-simple-search__field']"
itemname_locator = "//*[@itemprop='name']"
proceedcheckout_locator = "//*[@class='c-cart-buttons ']/div/button"
zipcode_locator = "//input[@id='dwfrm_billing_billingAddress_addressFields_zip']"
prefectures_locator = "//select[@id='dwfrm_billing_billingAddress_addressFields_district']"
address_locator = "//input[@id='dwfrm_billing_billingAddress_addressFields_city']"
numberaddress_locator = "//input[@id='dwfrm_billing_billingAddress_addressFields_address1']"
